### ISSUE TITLE
Proposition d'amélioration : Intégration de TypeScript et refonte de l'API des modules 🚀

### ISSUE THREAD

**Issue by ilyeshernandez1** [bacherobot/bot#6]
## Objectif
Cette proposition vise à moderniser le code actuel en introduisant TypeScript et à repenser l'API des modules pour en faciliter l'utilisation.

### 1. **Adoption de TypeScript :**
   - **Avantages :**
      - Typage statique pour une détection précoce des erreurs.
      - Générer une documentation dynamique grâce au typage.
      - Améliorer la lisibilité et la maintenabilité du code.

### 2. **Refonte de l'API des Modules :**
   - **Objectif :**
      - Proposer une API plus conviviale et cohérente.
      - Développement d'une librairie TypeScript pour faciliter l'interaction avec les outils du bot.

---

N'hésitez pas à ajuster selon vos besoins !

**Comment by johan-perso** [comment]
Salut ! Personnellement, j'suis pas trop fan du TypeScript et j'pense pas l'adopter dans un de mes codes avant pas mal de temps. Une refonte de l'API interne aura également lieu dans quelques mises à jour majeures, mais c'est compliqué à planifier car cela provoquerait beaucoup de breaking changes.

**Comment by ilyeshernandez1** [comment]
Okay! Je comprend, mais n'hésite pas à revoir un peu la mnaière dont le code est structuré (genre séparer les fichiers) car j'ai essayer de contribuer au code mais malheureusement j'ai du mal à suivre, ce que je veux dire par là c'est que c'est un peu compliqué de comprendre le code si celui-ci est centralisé sur un seule fichier. J'aurais dis plutôt de séparer les fichiers mais de potentiellement exporter toutes les fonctions utilitaires dans un fichier unique.

**Comment by ilyeshernandez1** [comment]
Sinon, je voudrais bien contribuer au code 😄

**Comment by johan-perso** [comment]
J'peux comprendre que ça peut être compliqué de lire le code dans un fichier aussi long, j'trouve cependant que ça pourrait être compliqué et pas si bénéfique que ça de séparer les fonctions dans différents fichiers, peut-être que j'suis juste trop habitué à ça perso, mais j'risque pas de changer ça avant la màj majeure dont j'ai parlé dans le précédant message qui changerait beaucoup d'éléments dans le code.

J'te laisse volontiers contribuer au code si t'en a la motivation ! Une courte [page dans la doc](https://bachero.johanstick.fr/docs/contribute) explique comment contribuer au repo GitHub.

**Comment by ilyeshernandez1** [comment]
Je vais voir cela assez rapidement :)
